"
" MAIN CUSTOMIZATION FILE
"

" Enable loading filetype and indentation plugins
filetype plugin on
filetype indent on

" Turn syntax highlighting on
syntax on

"
" GLOBAL SETTINGS
"

set nu
set ignorecase


" Write contents of the file, if it has been modified, on buffer exit
set autowrite

" Allow backspacing over everything
set backspace=indent,eol,start

" Insert mode completion options
set completeopt=menu,longest,preview

" Use UTF-8 as the default buffer encoding
set enc=utf-8

" Remember up to 100 'colon' commmands and search patterns
set history=100

" Enable incremental search
set incsearch

" Always show status line, even for one window
set laststatus=2

" Jump to matching bracket for 2/10th of a second (works with showmatch)
set matchtime=2

" Don't highlight results of a search
set nohlsearch

" Enable CTRL-A/CTRL-X to work on octal and hex numbers, as well as characters
set nrformats=octal,hex,alpha

" Use F10 to toggle 'paste' mode
set pastetoggle=<F10>
"set buftype=''
" Show line, column number, and relative position within a file in the status line
set ruler

" Scroll when cursor gets within 3 characters of top/bottom edge
set scrolloff=3

" Round indent to multiple of 'shiftwidth' for > and < commands
set shiftround

" Use 4 spaces for (auto)indent
set shiftwidth=4

" Show (partial) commands (or size of selection in Visual mode) in the status line
set showcmd

" When a bracket is inserted, briefly jump to a matching one
set showmatch

" Don't request terminal version string (for xterm)
set t_RV=

" Use 4 spaces for <Tab> and :retab
set tabstop=4

" Write swap file to disk after every 50 characters
set updatecount=50

" Remember things between sessions
"
" '20  - remember marks for 20 previous files
" \"50 - save 50 lines for each register
" :20  - remember 20 items in command-line history 
" %    - remember the buffer list (if vim started without a file arg)
" n    - set name of viminfo file
set viminfo='20,\"50,:20,%,n~/.viminfo

" Use menu to show command-line completion (in 'full' case)
set wildmenu

" Set command-line completion mode:
"   - on first <Tab>, when more than one match, list all matches and complete
"     the longest common  string
"   - on second <Tab>, complete the next full match and show menu
set wildmode=list:longest,full

" Go back to the position the cursor was on the last time this file was edited
au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")|execute("normal `\"")|endif

" Fix my <Backspace> key (in Mac OS X Terminal)
" set t_kb=
" fixdel

" Avoid loading MatchParen plugin
let loaded_matchparen = 1

" netRW: Open files in a split window
let g:netrw_browse_split = 1

"
" MAPPINGS
"

" save changes
map ,w :w<CR>
" exit vim without saving any changes
map ,q :q!<CR>
" exit vim saving changes
map ,x :x<CR>
" switch to upper/lower window quickly
map <C-J> <C-W>j
map <C-K> <C-W>k
" use CTRL-F for omni completion
imap <C-F> 
" map ,f to display all lines with keyword under cursor and ask which one to
" jump to
nmap ,f [I:let nr = input("Which one: ")<Bar>exe "normal " . nr ."[\t"<CR>
" use <F6> to toggle line numbers
nmap <silent> <F6> :set number!<CR>
" page down with <Space>
"nmap <Space> <PageDown>
" open filename under cursor in a new window (use current file's working
" directory) 
nmap gf :new %:p:h/<cfile><CR>
" map <Alt-p> and <Alt-P> to paste below/above and reformat
nnoremap <Esc>P  P'[v']=
nnoremap <Esc>p  p'[v']=
" visual shifting (does not exit Visual mode)
vnoremap < <gv
vnoremap > >gv 

" map cc cx comlents //
map cc v:s/^/\/\//g<CR>
map cx v:s/^\/\///g<CR>

" map cc cx comments //
vmap cc :s/^/\/\//g<CR>
vmap cx :s/^\/\///g<CR>


" Generic highlight changes
highlight Comment cterm=none ctermfg=Gray
highlight IncSearch cterm=none ctermfg=Black ctermbg=DarkYellow
highlight Search cterm=none ctermfg=Black ctermbg=DarkYellow
highlight String cterm=none ctermfg=DarkGreen
highlight treeDir cterm=none ctermfg=Cyan
highlight treeUp cterm=none ctermfg=DarkYellow
highlight treeCWD cterm=none ctermfg=DarkYellow
highlight netrwDir cterm=none ctermfg=Cyan


"
" NERDTree configuration
"

" Increase window size to 35 columns
let NERDTreeWinSize=35

" map <F7> to toggle NERDTree window
nmap <silent> <F7> :NERDTreeToggle<CR>
nmap cl :%s/[ ]\{1,\}\n/\r/g<CR>


" set encoding=utf-8
" set fileencoding=chinese
" set fileencodings=ucs-bom,utf-8,chinese
" set ambiwidth=double

set fencs=utf-8,gbk,gb2312

if has("autocmd")
"	autocmd FileType python set dictionary+=/home/panrui/.vim/pydiction-0.5/pydiction
"	autocmd FileType python set complete+=k
	autocmd FileType python set complete+=k/home/lahmwen/.vim/pydiction-0.5/pydiction isk+=.,( 
endif

" map <F12> to toggle NERDTree window
nmap <silent> <F12> :set list!<CR>
set list
set lcs=tab:>-,trail:-

"" del space 
" map ds delete space
nmap <silent> <F9> :%s/\s\+$//g<CR>
"map  ds v:%s/\s\+$//g<CR>
"vmap ds  :%s/\s\+$//g<CR>
"
"
"
"map cp :w<CR>:!cp % /tmp/% <CR><CR>
map cp :w<CR>:!insmeishi % <CR><CR>
map cs :w<CR>:!inscss <CR><CR>
map ml :w<CR>:!insmyql % <CR><CR>
map pp :w<CR>:!php -l % <CR>
map pr :w<CR>:!php % <CR>
map pu :w<CR>:!phpunit % <CR>
map ms8 :w<CR>:!upload -t ms218 % <CR><CR>
map ms9 :w<CR>:!upload -t ms219 % <CR><CR>
map mst :w<CR>:!upload -t ms221 % <CR><CR>
map ms1 :w<CR>:!upload -t msdev1 % <CR><CR>
map ms2 :w<CR>:!upload -t msdev2 % <CR><CR>
map ms3 :w<CR>:!upload -t msdev3 % <CR><CR>
map ms4 :w<CR>:!upload -t msdev4 % <CR><CR>
map ms5 :w<CR>:!upload -t msdev5 % <CR><CR>

" set color schema
" colorscheme bluegreen
" colorscheme torte

map dc :r! date +\%Y年\%m月\%d日\ \%H:\%M:\%S <CR>

" use space instead of tab
"set expandtab

:map 11 :tabnext 1<CR>
:map 22 :tabnext 2<CR>
:map 33 :tabnext 3<CR>
:map 44 :tabnext 4<CR>
:map 55 :tabnext 5<CR>
:map 66 :tabnext 6<CR>
:map 77 :tabnext 7<CR>
:map 88 :tabnext 8<CR>

map <C-B> :BufSurfBack<CR>
map <C-F> :BufSurfForward<CR>

" zencoding
let g:user_zen_expandabbr_key = '<c-y>'
let g:use_zen_complete_tag = 1
